### ISSUE TITLE
EndeavourOS URL in prof needs updating

### ISSUE THREAD

**Issue by lissy93** [EndeavourOS/ISO#1]
Hey,

The URL in your the GitHub bio for [@EndeavourOS](https://github.com/EndeavourOS) `http://www.endeavouros.com/` returns a 404, and should be updated to `https://endeavouros.com/` (just without the www).

This is the one ([screenshot](https://user-images.githubusercontent.com/1862727/193478036-4e728435-cd23-40b2-b57f-fd0126676f43.png)) I'm referring to, and you can update it under https://github.com/settings/profile

I'm not sure if this is the official repo, but I thought I'd let you know since this GH account is linked to from the Arch docs, so it'd be good to have the correct URL in the bio :)

**Comment by killajoe** [comment]
thank`s i will go fix this!

**Comment by killajoe** [comment]
@EndeavourOS

**Comment by EndeavourOS** [comment]
Thaks, it has been changed
